services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    openweathermap.http_client:
        class: GuzzleHttp\Client

    OpenWeatherMapClient\Client\ApiClient:
        arguments:
            $httpClient: '@openweathermap.http_client'